apiVersion: v1
kind: Pod
metadata:
  name: recyclothes-pod
  labels:
    app: recyclothes
spec:
  containers:
    - name: restserver-upload
      image: nginx:alpine
      env:
        - name: DIR_CLOTHES_PENDIENTE
          valueFrom:
            configMapKeyRef:
              name: recyclothes-cm
              key: directorioPendiente
        - name: DIR_CLOTHES_ONLINE
          valueFrom:
            configMapKeyRef:
              name: recyclothes-cm
              key: directorioOnline
      volumeMounts:
        - mountPath: "/var/share/nginx/html"
          name: recyclothes-volume
  volumes:
    - name: recyclothes-volume
      persistentVolumeClaim:
        claimName: recyclothes-pvc
