apiVersion: v1
kind: PersistentVolume
metadata:
  name: recyclothes-pv
  labels:
    app: recyclothes
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/recyclothes"
      