apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclothes-pvc
  labels:
    app: recyclothes
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi