apiVersion: v1
kind: Service
metadata:
  name: recyclothes-service
  labels:
    app: recyclothes
spec:
  type: ClusterIP
  selector:
    app: recyclothes-deployment
  ports:
    - protocol: TCP
      port: 80